### ISSUE TITLE
No more `extern crate`

### ISSUE THREAD

**Issue by vayn** [lilydjwg/capture-dns#1]
https://github.com/lilydjwg/capture-dns/blob/34d54a4080d6f02544914a781b8ad5e9631dc3d0/src/main.rs#L1

Rust 2018 之后不需要这一行了

https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#no-more-extern-crate
https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macro_rules-style-macros

**Comment by lilydjwg** [comment]
忘了还能这样了。

**Comment by vayn** [comment]
> 忘了还能这样了。

原来的语法别扭地很，更新以后保持一致了
